name: irfanarif
favicon: null
layout_spectrum: 0.00653
typography_spectrum: 0.19021
title: Irfan Arif
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f0fd'
    - '#051c1e'
    - '#f1c09c'
    - '#9f8b7f'
    - '#b75832'
  brandStrength: 0.9491131354589015
  lightness: 0.38339876173995435
  saturation: 0.9927553243469447
  rhythmicContrast: 0.6655621863901615
purpose: []
